project_id = "nwljwmdiyflkmgsemmbm"

[functions.gym-chatbot]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-invoice-email]
verify_jwt = true

[functions.send-mass-email]
verify_jwt = true

[functions.notify-waitlist]
verify_jwt = true

[functions.send-class-reminders]
verify_jwt = true

[functions.admin-update-user]
verify_jwt = true

[functions.admin-get-users]
verify_jwt = true

[functions.admin-toggle-user-status]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.crm-workflow-executor]
verify_jwt = true

[functions.translate-content]
verify_jwt = true

[functions.notify-class-deletion]
verify_jwt = true

[functions.notify-class-status-change]
verify_jwt = true
